version: "3.3"
services:
  chromedriver:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    container_name: chromedriver
    environment:
      SE_NODE_MAX_SESSIONS : 10
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123A!
      POSTGRES_DB: mcil
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: db
  app:
    depends_on:
      - db
      - chromedriver
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - "SPRING_THYMELEAF_PREFIX=classpath:/templates/"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=test123A!"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mcil"
      - "CHROMEDRIVER_REMOTE_URL=http://chromedriver:4444/wd/hub"
      - "SPRING_PROFILES_ACTIVE=docker-prod"
volumes:
  db-data: